# Generated by Django 5.2 on 2025-04-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveSmallIntegerField()),
                ('concentration', models.CharField(choices=[('CORE', 'Core'), ('DS', 'Data Science'), ('CS', 'Computer Science'), ('ELECTIVE', 'Elective'), ('PREP', 'Preparatory')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('concentration', models.CharField(choices=[('DS', 'Data Science'), ('CS', 'Computer Science')], max_length=10)),
                ('completed_courses', models.ManyToManyField(blank=True, to='planner.course')),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_course', to='planner.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='planner.course')),
            ],
            options={
                'unique_together': {('course', 'prerequisite')},
            },
        ),
    ]
